pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Preparing env') {
            steps {
                script {
                    def nodeHome = tool name: 'nodejs', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
                    if (nodeHome == null) {
                        echo 'Node.js not found. Installing...'
                        nodeHome = tool name: 'nodejs', type: 'jenkins.plugins.nodejs.tools.NodeJSInstaller'
                    }
                    env.PATH = "${nodeHome}/bin:${env.PATH}"
                }
            }
        }

        stage('Clone Repository') {
            steps {
                script {
                    sh "git clone ${Repository} ."
                }
            }
        }

        stage('Running the app') {
            steps {
                script {
                    sh "node ${AppFile}"
                }
            }
        }
    }
}
