pipeline {
   agent {
        docker { image 'node:20' }
    }

    parameters {
        string(name: 'repository', defaultValue: '', description: 'The Repository Link')
        booleanParam(name: 'hasBuild', defaultValue: false, description: 'Does this app have build step?')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        
        stage('Clone Repository') {
            steps {
                script {
                    sh "git clone ${params.repository} ."
                }
            }
        }

        stage('Add the dependencies') {
            steps {
                script {
                    sh "npm install  --ignore-scripts"
                }
            }
        }

        stage('Build the app') {
            when {
                expression { params.hasBuild }
            }
            steps {
                script {
                    sh "npm run build"
                }
            }
        }
    }
}
